# default build type
if (NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING "build type" FORCE)
endif()

#enabling ipo
if (ENABLE_IPO)
	if("${CMAKE_VERSION}" VERSION_GREATER 3.9)
		cmake_policy(GET CMP0069 cmpcheck)
		if (NOT cmpcheck STREQUAL NEW)
			cmake_policy(SET CMP0069 NEW)
		else()
			message("already new")
		endif()
		cmake_policy(GET CMP0069 cmpcheck)

		include(CheckIPOSupported)
		check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error)
		if (ipo_error)
			messsage(WARNING "ipo error: ${ipo_error}")
		elseif(ipo_supported)
			set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
		else()
			if (NOT warned_ipo_support)
				message(WARNING "IPO not supported")
			endif()
			set(warned_ipo_support ON STRING "already warned")
		endif()
	else()
		if (NOT warned_ipo_vs)
			message(WARNING "IPO requires cmake >= 3.9, current version is ${CMAKE_VERSION}")
		endif()
		set(warned_ipo_vs ON STRING "already warned")
	endif()
endif()
